prisma/language-tools

README.md

Previously showed Page Not Found. Now it directs to the correct URL.

Fixed the "here" link.

---

.gitignore
Readme.md
package.json
src/install.ts
yarn.lock

Todo:
Resolves: https://github.com/prisma/prisma-engine/issues/212 https://github.com/prisma/prisma-engine/issues/211

fix url link

---

src/extension.ts

3rd time's a charm? 
- add the extension path for windows
- cleanup a bit of inconsistently formatted code

add .exe extension to fix windows

---

Readme.md

To get around the 1 year PAT limitation. I will create a recurring yearly yearly meeting.

chore: add auto release process description

---

scripts/bump-sha.sh
scripts/publish.sh

fixes https://github.com/prisma/vscode/issues/68

feat(auto-publish): bump sha

---

syntaxes/prisma.tmLanguage.json

Fix highlight for model when no space is present

---

scripts/bump-sha.sh
scripts/prisma-version.sh

TODO: Readme might also need a link update once we know where the new
files are.

fix(cli): adjust for prisma2 cli name change

---

scripts/bump.sh

https://github.com/koalaman/shellcheck/wiki/SC2103
Only failed on Linux and not mac for some reason

fix(lint): shell lint SC2103

---

client/src/test/jumpToDefinition.test.ts
client/testFixture/autoFormat.prisma
client/testFixture/correct.prisma
server/src/MessageHandler.ts

fix(go_to_definition): Improve matching of models

---

server/src/lint.ts
server/src/server.ts

Recognize Prisma1 schemas and tell user to install the other extension and rename file

---

server/src/server.ts

feat(additional info on startup)

---

README.md

Using svg breaks marketplace publish.

remove .svg for now

---

.github/workflows/continuous-integration.yml

improvement(ci): trigger CI on release events too

---

server/src/completions.ts

bug(auto-completion): suggest current model for self relation

---

server/src/server.ts

closes #168
adds binary hash to output on startup

fix(console): output binary hash again

---

server/src/server.ts
server/src/util.ts

improvement(startup): include CLI version in startup output

---

README.md

closes #181 
uses schema from Prisma Docs  https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema

improvement(README): use schema from the docs

---

server/src/MessageHandler.ts
server/src/completions.ts

bug(auto-completion): fix suggestions for @relation directive

---

README.md

improvement(README): Include badges again

---

scripts/bump.sh

improvement(naming): change extension name, description and preview to insider

---

server/src/completions.ts
server/src/format.ts
server/src/lint.ts
server/src/server.ts

fix(prisma1): Recognize prisma1 schemas again

---

.github/workflows/continuous-integration.yml

context: https://github.com/prisma/vscode/pull/202#issuecomment-639431714

improvement(CI): add test to check for shell script issues automatically

---

client/src/test/completion.test.ts
server/src/MessageHandler.ts
server/src/completion/completions.ts

improvement(auto-completion): add modifiers to type suggestions

---

scripts/bump.sh
scripts/prisma-version.sh

TODO: Test this and merge after the release has happened.

feat: use dev, latest channels from npm

---

client/src/test/completion.test.ts
server/src/completion/completionUtil.ts
server/src/completion/completions.json
server/src/completion/completions.ts

bug(auto-completion): fix cursor position for relation directive arguments

---

server/src/MessageHandler.ts

bug(auto-completion): remove suggestions after block types

---

server/src/MessageHandler.ts
server/src/completion/completionUtil.ts
server/src/completion/completions.json
server/src/completion/completions.ts
server/src/util.ts

improvement(auto-completion): add env() support

---

server/src/MessageHandler.ts

bug(auto-completion): fix suggestions for block when typing already

---

package.json

improvement(CI): clean build before publish

---

README.md
scripts/README_INSIDER_BUILD.md
scripts/README_STABLE_BUILD.md

improvement(README): document format on save 

---

server/src/server.ts
server/src/util.ts

improvement(prisma-fmt): try to execute binary in isBinaryNeededCheck

---

package.json

bug(lerna): use workaround for lerna bootstrap

---

scripts/README_INSIDER_BUILD.md
scripts/README_STABLE_BUILD.md
scripts/publish.sh

docs(README): Remove logo

---

packages/language-server/src/codeActionProvider.ts

fix: spelling suggestion with type modifiers

---

packages/language-server/src/MessageHandler.ts
packages/language-server/src/completion/completionUtil.ts
packages/language-server/src/completion/completions.json
packages/language-server/src/completion/completions.ts
packages/language-server/src/server.ts
packages/vscode/src/extension.ts
packages/vscode/src/test/completion.test.ts
packages/vscode/testFixture/completions/datasourceWithSqlite.prisma
packages/vscode/testFixture/completions/datasourceWithUrl.prisma

feat(auto-completion): support for multiple providers

---

scripts/bump.sh

ci: keep root package.json in sync with subfolders

---

scripts/publish.sh

ci(publish): use rebase instead of fast forward only

---

packages/language-server/src/server.ts

fix: add binaryCheck again

---

packages/language-server/src/completion/completions.json
packages/language-server/src/completion/completions.ts
packages/language-server/src/test/completion.test.ts
packages/language-server/test/fixtures/completions/modelBlocks.prisma

test: add updatedAt attribute

---

.github/workflows/publish.yml
package.json
scripts/lsp-version.sh

ci: check existing lsp version before publish

---

packages/vscode/src/extension.ts
packages/vscode/src/util.ts

style: implement client-side of snippetTextEdit

---

packages/language-server/src/completion/completionUtil.ts
packages/language-server/src/completion/completions.json
packages/language-server/src/completion/completions.ts

fix: auto-completion for generator provider argument

---

packages/language-server/src/completion/completions.ts
packages/language-server/src/test/completion.test.ts
packages/language-server/test/fixtures/completions/modelBlocks.prisma
packages/vscode/src/test/completion.test.ts

fix: autocompletion suggesting unique only once per model block

---

packages/vscode/syntaxes/prisma.tmLanguage.json

fix: remove end of line symbol in enum value regexp

---

packages/language-server/src/MessageHandler.ts
packages/language-server/src/codeActionProvider.ts

chore: warning on experimentalFeatures property and quick-fix

---

.vscode/settings.json
packages/language-server/src/server.ts
packages/vscode/src/extension.ts

feat: workaround for hanging types

---

packages/vscode/package.json
packages/vscode/syntaxes/prisma.js.json

feat: add support for inline prisma syntax highlighting

---

.github/workflows/patch-CLI.yml
.github/workflows/patch-extension-only.yml
.github/workflows/publish-insider-check-CLI.yml
.github/workflows/publish-insider-push-master.yml
.github/workflows/publish-patch-branch-to-stable.yml
.github/workflows/publish-stable.yml

Also increases the scheduled time the workflows get triggered from 5/10 to 15, since the workflows take about 12 min to complete.

Fix script to run even if some got skipped

---

packages/language-server/src/MessageHandler.ts
packages/language-server/src/completion/completions.ts
packages/language-server/src/rename/renameUtil.ts
packages/language-server/src/test/rename.test.ts
packages/language-server/test/fixtures/rename/renameFieldLargeSchema.prisma

closes #359 
- renames on relation fields are now not possible any more
- bug renaming unrelated fields fixes

fix: Bug in rename function

---

README.md
packages/language-server/CONTRIBUTING.md
packages/language-server/Readme.md
packages/vscode/CONTRIBUTING.md

chore: update dev instructions for working with language server

---

.vscode/launch.json
packages/language-server/CONTRIBUTING.md
packages/vscode/src/extension.ts

chore: streamline debugging of language server

---

packages/vscode/src/extension.ts
packages/vscode/src/util.ts

fix: broken 2.4.0 release

---

packages/vscode/src/util.ts

fix: workaround for mutating VSCode config objects

---

.github/workflows/patch-CLI.yml
.vscodeignore
scripts/publish.sh

Also exclude all files not needed at runtime for the extension.

fix: publish and push to branch

---

packages/language-server/src/MessageHandler.ts
packages/language-server/src/test/rename.test.ts
packages/language-server/test/fixtures/rename/renameModelWithJsonDefault.prisma

fix: renaming model name in a model with a JSON default value

---

packages/language-server/src/MessageHandler.ts
packages/language-server/src/rename/renameUtil.ts
packages/language-server/src/test/rename.test.ts

closes #394 
Allows renaming and applying @@map on both model and enums on definition and where used as types.

improvement: rename model where used as type

---

scripts/README_STABLE_BUILD.md

docs: document rename functionality better for marketplace README

---

packages/vscode/src/blackListColorThemes.ts
packages/vscode/src/denyListColorThemes.ts
packages/vscode/src/extension.ts
packages/vscode/src/util.ts

chore: detect VSCode theme

---

packages/language-server/src/completion/completionUtil.ts
packages/language-server/src/completion/completions.json
packages/language-server/src/test/completion.test.ts
packages/vscode/src/test/completion.test.ts

fix: @@map and @map initialization via auto-completion

---

packages/vscode/src/extension.ts

chore: remove window notification for TS Server restart

---

scripts/change_readme.js

fix: read version of Prisma CLI in change-readme

---

packages/vscode/README.md
scripts/README_INSIDER_BUILD.md
scripts/README_STABLE_BUILD.md

Reorganize readme

---

.github/workflows/1_2_b_bump_extension_only.yml
.github/workflows/1_2_c_promote_patch_to_stable.yml
.github/workflows/1_check_for_updates.yml
.github/workflows/2_bump_versions.yml
.github/workflows/3_LSP_unit_tests_publish.yml
.github/workflows/4_bump_LSP_in_extension.yml
.github/workflows/5_e2e_tests.yml
.github/workflows/6_build.yml

chore: Slack notifications for failures on any workflow

---

.github/workflows/1_2_b_bump_extension_only.yml
.github/workflows/1_2_c_promote_patch_to_stable.yml
.github/workflows/1_check_for_updates.yml
.github/workflows/2_bump_versions.yml
.github/workflows/3_LSP_unit_tests_publish.yml
.github/workflows/4_bump_LSP_in_extension.yml
.github/workflows/5_e2e_tests.yml
.github/workflows/6_build.yml
.github/workflows/7_publish.yml

chore: add number of CI step in visible name of workflow

---

README.md
packages/vscode/README.md

chore: include e2e tests badges in READMEs

---

packages/language-server/src/completion/completions.json

- removes `insensitive Filters`

chore: update feature flag auto-completion list

---

packages/language-server/src/completion/completions.ts

fix: autocomplete stops stops showing after first character

---

.github/workflows/1_2_b_bump_extension_only.yml
.github/workflows/1_2_c_promote_patch_to_stable.yml
.github/workflows/2_bump_versions.yml
.github/workflows/3_LSP_unit_tests_publish.yml
.github/workflows/4_bump_LSP_in_extension.yml
.github/workflows/5_e2e_tests.yml
.github/workflows/6_build.yml
.github/workflows/7_publish.yml

add Ci trigger reason

---

packages/language-server/src/codeActionProvider.ts

feat: spelling suggestion for wrong block names

---

packages/language-server/package-lock.json
packages/vscode/src/extension.ts
packages/vscode/src/plugins/index.ts
packages/vscode/src/plugins/prisma-language-server/index.ts
packages/vscode/src/plugins/types.ts

Reverts prisma/language-tools#535
Don't ask -_-

Revert "Revert "feat(vscode): pluginify services""

---

packages/language-server/bin/prisma-language-server
packages/language-server/package.json

resolves https://github.com/prisma/language-tools/issues/566

fix: use shebang for binary entrypoint

---

packages/vscode/src/plugins/prisma-language-server/index.ts

Fixes a path that was changed [here](https://github.com/prisma/language-tools/pull/568)

fix: path to LSP

---

packages/vscode/src/plugins/nextjs/addTSType.ts
packages/vscode/src/plugins/nextjs/index.ts
packages/vscode/src/plugins/nextjs/nextTypes.ts
packages/vscode/src/plugins/nextjs/tests/__fixtures__/regressions.ts
packages/vscode/src/plugins/nextjs/tests/__snapshots__/regressions.test.ts.snap
packages/vscode/src/plugins/nextjs/tests/regressions.test.ts

fix(vscode): nextjs plugin fliping function params

---

packages/language-server/src/server.ts

fix: console.log in server

---

packages/language-server/src/MessageHandler.ts
packages/language-server/src/completion/completions.ts

Reverts prisma/language-tools#598

fix(native-types): revert "chore: comment native types"

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository

chore: issue template

---

packages/language-server/package-lock.json
packages/language-server/package.json
packages/language-server/src/prisma-fmt/install.ts
renovate.json
scripts/update_package_json_files.js

Adds HTTP proxy support 
related https://github.com/prisma/language-tools/issues/403

feat: http proxy support

---

packages/language-server/src/completion/completions.ts
packages/language-server/src/rename/renameUtil.ts
packages/language-server/src/test/rename.test.ts
packages/language-server/test/fixtures/rename/renameMultipleModels.prisma

fixes https://github.com/prisma/language-tools/issues/636

fix: rename multiple models of same relation

---

packages/language-server/src/MessageHandler.ts
packages/language-server/src/test/rename.test.ts
packages/language-server/test/fixtures/rename/renameModelBug.prisma

fix: rename bug

---

package.json
packages/language-server/src/codeActionProvider.ts
packages/language-server/src/completion/completionUtil.ts
packages/language-server/src/test/completion.test.ts
packages/vscode/src/test/completion.test.ts

Closes https://github.com/prisma/language-tools/issues/697

fix: remove nativeTypes flag quick fix

---

packages/language-server/src/completion/completions.json
packages/language-server/src/test/completion.test.ts
packages/vscode/src/test/completion.test.ts

@albertoperdomo Can you check to see if the documentation needs more?
Closes #708

feat(lang-server): Add autocomplete for shadowDatabaseUrl

---

packages/vscode/syntaxes/prisma.tmLanguage.json

fix: syntax highlighting for abnormal phrases like Strings

---

packages/vscode/README.md
scripts/README_STABLE_BUILD.md

closes https://github.com/prisma/language-tools/issues/666

docs: note about prettier in combination with format

---

.github/workflows/continuous-integration.yml
package-lock.json
package.json
scripts/__tests__/__snapshots__/change-readme.test.js.snap
scripts/__tests__/dependencies.test.js

- check for a smaller or equal version for `@types/vscode` and `engine.version`
- updates snapshots

chore: CI test for version incompatibilities

---

.eslintrc.js
packages/language-server/src/completion/completions.json
packages/language-server/src/test/completion.test.ts
packages/vscode/src/test/completion.test.ts

fix: autocompletion for @@map

---

packages/language-server/src/server.ts
packages/language-server/src/settings.ts
packages/language-server/src/test/linting.test.ts
packages/language-server/src/util.ts
packages/language-server/test/fixtures/linting/wrongType.prisma
packages/vscode/src/plugins/prisma-language-server/index.ts
packages/vscode/src/test/linting.test.ts
packages/vscode/src/util.ts

See failed test https://github.com/prisma/language-tools/runs/2620801441?check_suite_focus=true#step:5:92
Not sure why it's needed to update this. Looks ok to me but it's weird and not sure what it means?

test: fix Linting Wrong type test

---

package-lock.json
package.json

Fixes https://github.com/prisma/language-tools/pull/832

test: fix - add missing vscode-test dependency

---

.github/workflows/1_2_b_bump_extension_only.yml
.github/workflows/1_2_c_promote_patch_to_stable.yml
.github/workflows/2_bump_versions.yml
README.md
packages/vscode/CONTRIBUTING.md
packages/vscode/README.md
packages/vscode/release-workflow.md
scripts/README_INSIDER_BUILD.md
scripts/README_STABLE_BUILD.md
scripts/__tests__/__snapshots__/change-readme.test.js.snap
scripts/__tests__/extension-version.test.js
scripts/bump_extension_version.js
scripts/commit_and_push.sh
scripts/setup_branch.sh

This should only be merged at the same time we do the rename via GH UI.

chore: master => main

---

packages/language-server/src/MessageHandler.ts
packages/language-server/src/completion/completionUtil.ts
packages/language-server/src/completion/completions.ts
packages/language-server/src/server.ts
packages/language-server/src/util.ts

Small improvements while reading code and going through fixes

chore: comments and small improvements

---

.github/workflows/1_check_for_updates.yml
.github/workflows/2_bump_versions.yml
.github/workflows/4_bump_LSP_in_extension.yml
.github/workflows/6_build.yml
.github/workflows/7_publish.yml
scripts/__tests__/extension-version.test.js
scripts/bump_extension_version.js
scripts/check_for_update.js
scripts/is_minor_or_major_release.js
scripts/update_package_json_files.js

Context https://prisma-company.slack.com/archives/C02DT08SULR/p1630968516000500

ci(publish): special condition for prisma 3.0.1

---

.github/workflows/2_bump_versions.yml
.github/workflows/3_LSP_unit_tests_publish.yml
.github/workflows/4_bump_LSP_in_extension.yml
.github/workflows/5_e2e_tests.yml
.github/workflows/6_build.yml
.github/workflows/7_publish.yml

Make sure **all** the inputs are output again in the same order as input.

ci(actions): Make sure "Print outputs" prints everything everywhere

---

packages/language-server/src/test/completion.test.ts

Closes https://github.com/prisma/language-tools/issues/924

test(lsp): increase timeout for completions tests

---

packages/language-server/src/completion/completions.ts
packages/language-server/src/test/completion.test.ts
packages/language-server/test/fixtures/completions/relationDirectiveSqlserverReferentialActions.prisma
packages/vscode/src/test/completion.test.ts
packages/vscode/testFixture/completions/relationDirectiveSqlserverReferentialActions.prisma

Closes https://github.com/prisma/language-tools/issues/927

feat: add datasource provider detection & remove Restrict if SQLServer

---

packages/vscode/CONTRIBUTING.md
packages/vscode/README.md
packages/vscode/TESTING.md
packages/vscode/package.json
packages/vscode/src/plugins/prisma-language-server/index.ts
scripts/README_STABLE_BUILD.md
scripts/__tests__/__snapshots__/change-readme.test.js.snap

Also had to disable a bunch of eslint rules to be able to commit the index.ts of the plugin :/

chore: Cosmetic changes in README, code and comments

---

packages/vscode/src/plugins/prisma-language-server/index.ts
packages/vscode/src/util.ts

See internal discussion https://prisma-company.slack.com/archives/CKCQQGXJM/p1637780511103100

docs: comments about code that is part of #311

---

packages/language-server/src/completion/completionUtil.ts
packages/language-server/src/completion/completions.json
packages/language-server/src/completion/completions.ts
packages/language-server/src/test/completion.test.ts
packages/vscode/src/test/completion.test.ts

Related 
https://github.com/prisma/language-tools/pull/996
https://github.com/prisma/language-tools/issues/926

fix(extendedIndexes): postgres.postresql providers + @id: length, sort

---

packages/vscode/README.md
scripts/README_INSIDER_BUILD.md
scripts/README_STABLE_BUILD.md
scripts/__tests__/__snapshots__/change-readme.test.js.snap

GIFs from https://www.prisma.io/blog/vscode-extension-prisma-rust-webassembly

chore: update README with more gifs

---

packages/language-server/src/completion/completions.json
packages/language-server/src/test/completion.test.ts
packages/vscode/src/test/completion.test.ts

feat(server): add mongodb and cockroachdb providers

---

packages/vscode/README.md
scripts/README_INSIDER_BUILD.md
scripts/README_STABLE_BUILD.md
scripts/__tests__/__snapshots__/change-readme.test.js.snap

Some GIF currently don't show on the marketplace
https://marketplace.visualstudio.com/items?itemName=Prisma.prisma-insider

chore: try fix GIF disaplay for marketplace in README

---

packages/vscode/src/test/completion.test.ts

Added in https://github.com/prisma/language-tools/pull/1072

test: fix skipped VS Code tests

---

packages/language-server/src/__test__/completion.test.ts
packages/language-server/src/completion/completions.ts
packages/language-server/test/fixtures/completions/mongodb_embedded_m2m.prisma

Closes https://github.com/prisma/language-tools/issues/1075

fix(autocompletion): references in many-to-many relations

---

packages/language-server/src/completion/completions.ts

Closes https://github.com/prisma/language-tools/issues/1080

fix(autocompletion): @relation: always filter already used attributes

---

packages/language-server/src/__test__/completion.test.ts
packages/language-server/src/completion/completions.json
packages/language-server/src/completion/completions.ts

With additional, unrelated, spring cleanup along the way in completions.json
Related https://github.com/prisma/language-tools/pull/1116#pullrequestreview-940887199

fix: cleanup, remove completion for datasource multi provider

---

packages/language-server/src/__test__/completion.test.ts

Closes https://github.com/prisma/language-tools/issues/1134

test: add native types tests for CockroachDB 

---

.github/workflows/PR_build_extension.yml

ci: Automatically post comment with link to test built extension via GitPod

---

packages/language-server/src/__test__/completion.test.ts
packages/language-server/src/completion/completions.ts

Closes https://github.com/prisma/language-tools/issues/1198

fix: completion for attributes on a field referencing a composite type

---

packages/vscode/src/__test__/runTest.ts
packages/vscode/tsconfig.json

See run https://github.com/prisma/language-tools/runs/7741478605?check_suite_focus=true#step:7:20

ci: test minimum and latest VS Code versions

---

packages/vscode/README.md

add symbols and quick fix for references / @unique

chore(README): update features

---

packages/language-server/src/__test__/completion.test.ts
packages/language-server/src/completion/completionUtils.ts
packages/language-server/src/completion/completions.json
packages/language-server/src/completion/completions.ts
packages/language-server/src/previewFeatures.ts
packages/language-server/src/prisma-fmt/listAllAvailablePreviewFeatures.ts

Closes https://github.com/prisma/language-tools/issues/991

feat(ls): suggest relationMode: "prisma" or "foreignKeys" for referentialIntegrity preview feature

---

.github/workflows/1_2_b_bump_extension_only.yml
.github/workflows/1_2_c_promote_patch_to_stable.yml
.github/workflows/2_bump_versions.yml
.github/workflows/3_LS_tests_publish.yml
.github/workflows/4_bump_LS_in_extension.yml
.github/workflows/5_e2e_tests.yml
.github/workflows/6_build.yml
.github/workflows/7_publish.yml
.github/workflows/PR_build_extension.yml
.github/workflows/continuous-integration.yml
.github/workflows/e2e_published_vsix.yml

See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name

ci(gh): try run-name

---

packages/language-server/src/completion/completionUtils.ts

fix(completions): Extra `'` in contextual documentation

---

packages/language-server/src/MessageHandler.ts
packages/language-server/src/__test__/linting.test.ts
packages/language-server/src/__test__/quickFix.test.ts
packages/language-server/src/__test__/rename.test.ts
packages/language-server/src/diagnosticsHandler.ts
packages/language-server/src/rename/renameUtil.ts
packages/language-server/src/util.ts

fix: replace Number.MAX_SAFE_INTEGER/MAX_VALUE by i32 maximum

---

packages/language-server/src/__test__/completion.test.ts
packages/language-server/src/completion/completions.json
packages/language-server/src/completion/completions.ts

Co-authored-by: Julius de Bruijn <bruijn@prisma.io>
closes https://github.com/prisma/prisma/issues/16957

Added completion for @@schema

---

packages/language-server/src/MessageHandler.ts
packages/language-server/src/__test__/completion.test.ts
packages/language-server/src/completion/completions.json
packages/language-server/src/completion/completions.ts
packages/language-server/src/previewFeatures.ts
packages/language-server/src/util.ts
packages/vscode/syntaxes/prisma.tmLanguage.json

Co-authored-by: Julius de Bruijn <bruijn@prisma.io>
adds syntax highlighting and completions
closes #1346

feat: views support

---

packages/language-server/src/__test__/completion.test.ts
packages/language-server/src/completion/completionUtils.ts
packages/language-server/src/completion/completions.json
packages/language-server/src/completion/completions.ts

Closes https://github.com/prisma/language-tools/issues/1359
Note: docs PR https://github.com/prisma/docs/pull/4377

feat: add directUrl completion + better datasource/generator completions

---

packages/language-server/src/__test__/completion.test.ts
packages/language-server/src/completion/completions.json
packages/language-server/src/completion/completions.ts

feat(completions): type block

---

packages/language-server/src/__test__/completion.test.ts
packages/language-server/src/completion/completionUtils.ts
packages/language-server/src/completion/completions.json
packages/language-server/src/completion/completions.ts

Remove datasource completions

---

.github/workflows/4_bump_LS_in_extension.yml
.github/workflows/6_build.yml
package-lock.json
package.json
scripts/bump_extension_version.js
scripts/check_for_update.js
scripts/e2eTestsOnVsix/check_for_new_release.js
scripts/e2eTestsOnVsix/check_marketplace_version.js
scripts/e2eTestsOnVsix/install_extension.js
scripts/get_tag_name.js
scripts/is_minor_or_major_release.js
scripts/setup_branch.sh

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

chore: remove deprecated set-output

---

packages/language-server/package.json
packages/language-server/src/MessageHandler.ts
packages/language-server/src/__test__/rename.test.ts
packages/language-server/src/rename/renameUtil.ts
packages/language-server/test/fixtures/rename/renameType.prisma
packages/language-server/test/fixtures/rename/renameView.prisma

https://github.com/prisma/language-tools/assets/29753584/7e426249-ebb0-4189-95f8-d29fcc044f78
closes https://github.com/prisma/language-tools/issues/1135
closes https://github.com/prisma/language-tools/issues/1365

feat(ls): code action to rename views & types

---

package-lock.json
package.json
packages/vscode/package-lock.json
packages/vscode/package.json

closes #1425
Renamed since 2.15 https://github.com/microsoft/vscode-vsce/pull/791

chore: update package vsce -> @vscode/vsce

---

package.json
packages/language-server/package-lock.json
packages/language-server/package.json
packages/language-server/src/MessageHandler.ts
packages/language-server/src/WasmPanicRegistry.ts
packages/language-server/src/__test__/artificial-panic.test.ts
packages/language-server/src/__test__/quickFix.test.ts
packages/language-server/src/codeActionProvider.ts
packages/language-server/src/completion/completionUtils.ts
packages/language-server/src/completion/completions.ts
packages/language-server/src/prisma-schema-wasm/codeActions.ts
packages/language-server/src/prisma-schema-wasm/format.ts
packages/language-server/src/prisma-schema-wasm/lint.ts
packages/language-server/src/prisma-schema-wasm/listAllAvailablePreviewFeatures.ts
packages/language-server/src/prisma-schema-wasm/nativeTypes.ts
packages/language-server/src/prisma-schema-wasm/textDocumentCompletion.ts
packages/language-server/src/prisma-schema-wasm/util.ts
packages/language-server/src/server.ts
packages/language-server/src/util.ts
packages/language-server/src/wasm.ts
renovate.json
scripts/update_package_json_files.js

Must be merged for Prisma 5
Related to https://github.com/prisma/team-orm/issues/31

chore: rename fmt to schema-wasm

---

packages/vscode/src/telemetryReporter.ts
scripts/README_INSIDER_BUILD.md
scripts/README_STABLE_BUILD.md
scripts/__tests__/__snapshots__/change-readme.test.js.snap
scripts/update_package_json_files.js

Closes https://github.com/prisma/language-tools/issues/1463

fix(vscode): read telemetryLevel too, to decide if telemetry should be enabled

---

packages/vscode/src/telemetryReporter.ts

Fixes bug introduced in https://github.com/prisma/language-tools/pull/1465

fix(telemetry): fix setting ID

---

packages/language-server/src/__test__/linting.test.ts
packages/language-server/src/lib/code-actions/index.ts

See https://github.com/prisma/prisma-engines/pull/4813

fix(ls): an error string changed and needed to be updated

---

packages/language-server/src/__test__/helper.ts
packages/language-server/src/__test__/multifile/MultifileHelper.ts
packages/language-server/src/__test__/multifile/completion.test.ts
packages/language-server/src/__test__/multifile/hover.test.ts
packages/language-server/src/__test__/multifile/jumpToDefinition.test.ts
packages/language-server/src/__test__/multifile/linting.test.ts
packages/language-server/src/__test__/multifile/quickFix.test.ts
packages/language-server/src/__test__/multifile/rename.test.ts
packages/language-server/src/__test__/quickFix.test.ts
packages/language-server/src/__test__/rename.test.ts
packages/language-server/src/lib/Schema.ts
packages/language-server/src/lib/code-actions/rename.ts
packages/language-server/test/fixtures/multifile/complete-field-notype/Post.prisma
packages/language-server/test/fixtures/multifile/complete-field-notype/User.prisma
packages/language-server/test/fixtures/multifile/complete-field-notype/config.prisma
packages/language-server/test/fixtures/multifile/complete-field/Post.prisma
packages/language-server/test/fixtures/multifile/complete-field/User.prisma
packages/language-server/test/fixtures/multifile/complete-field/config.prisma
packages/language-server/test/fixtures/multifile/linting/Post.prisma
packages/language-server/test/fixtures/multifile/linting/User.prisma
packages/language-server/test/fixtures/multifile/linting/config.prisma
packages/language-server/test/fixtures/multifile/quick-fix/Profile.prisma
packages/language-server/test/fixtures/multifile/quick-fix/User.prisma
packages/language-server/test/fixtures/multifile/quick-fix/config.prisma
packages/language-server/test/fixtures/multifile/user-posts/Post.prisma
packages/language-server/test/fixtures/multifile/user-posts/User.prisma
packages/language-server/test/fixtures/multifile/user-posts/config.prisma

Basic tests for multifile schemas

---

packages/language-server/src/__test__/completion.test.ts
packages/language-server/src/lib/ast/configBlock.ts

fix(ls): preview features regex

---

packages/language-server/src/__test__/multifile/completion.test.ts
packages/language-server/src/lib/ast/nativeTypes.ts
packages/language-server/src/lib/completions/attributes.ts
packages/language-server/src/lib/completions/index.ts
packages/language-server/src/lib/completions/types.ts
packages/language-server/src/lib/prisma-schema-wasm/nativeTypes.ts
packages/language-server/test/fixtures/multifile/complete-native-type/Post.prisma
packages/language-server/test/fixtures/multifile/complete-native-type/config.prisma

fix: Native type completions on multifile schema

---

packages/language-server/src/__test__/quickFix/block.test.ts

https://github.com/prisma/language-tools/actions/runs/9447095502/job/26018168297
pending: https://github.com/prisma/prisma-engines/pull/4916

test(ls): windows newlines

---

.github/workflows/1_2_b_bump_extension_only.yml
.github/workflows/1_2_c_promote_patch_to_stable.yml
.github/workflows/1_check_for_updates.yml
.github/workflows/2_bump_versions.yml
.github/workflows/3_LS_tests_publish.yml
.github/workflows/4_bump_LS_in_extension.yml
.github/workflows/5_e2e_tests.yml
.github/workflows/6_build.yml
.github/workflows/7_publish.yml
.github/workflows/PR_build_extension.yml
.github/workflows/codeql-analysis.yml
.github/workflows/continuous-integration.yml
.github/workflows/e2e_check_for_new_published_vsix.yml
.github/workflows/e2e_published_vsix.yml

Follow up to https://github.com/prisma/language-tools/pull/1763
Some of the later steps still fail.

ci: Add `PRISMA_BOT_TOKEN` to more checkouts

---

.github/workflows/7_publish.yml

ci: Add --debug flag to debug publishing

---

.github/workflows/e2e_published_vsix.yml
packages/vscode/src/__test__/runTest.ts

revert:
- os changes
- github logging
- vscode logging

chore(ci): revert debugging changes

---

package-lock.json
package.json
packages/vscode/package-lock.json
packages/vscode/package.json
renovate.json

tentatively bump vsce to 2.29
add vsce to renovate ignore

deps: vsce

---

packages/language-server/src/lib/types.ts
packages/language-server/src/server.ts
packages/vscode/package.json

fix https://github.com/prisma/language-tools/issues/1827

feat: add enableDiagnostics setting

---

packages/vscode/src/plugins/prisma-postgres-manager/PrismaPostgresRepository.ts
packages/vscode/src/plugins/prisma-postgres-manager/management-api/api.d.ts

API types have been fixed to correctly incorporate the connection string. Required manual updates to the code to fix  compile/lint issues.

fix: update API types and adjust create project+db code

---

.github/workflows/continuous-integration.yml
.github/workflows/update-api-types.yml
packages/language-server/src/lib/MessageHandler.ts
packages/language-server/src/lib/ast/configBlock.ts
packages/language-server/src/lib/code-actions/index.ts
packages/language-server/src/lib/completions/attributes.ts
packages/vscode/src/plugins/prisma-postgres-manager/PrismaPostgresRepository.ts
packages/vscode/src/plugins/prisma-postgres-manager/ai-tools/PDPCreatePPGTool.ts
packages/vscode/src/plugins/prisma-postgres-manager/management-api/api.d.ts

- fix lint warnings and add linting to CI run
- update api types
- use bot token for "Update API Types" workflow to push to main directly without requiring a PR

fix: update api types and improve ci

---

packages/vscode/src/plugins/prisma-postgres-manager/commands/deployLocalDatabase.ts
packages/vscode/src/plugins/prisma-postgres-manager/index.ts

feat: Adds telemetry to local database deployment

---

packages/language-server/src/__test__/completions/single-file.test.ts
packages/language-server/src/lib/completions/attributes.ts
packages/language-server/src/lib/types.ts

Drop preview feature check and update tests.
https://linear.app/prisma-company/issue/ORM-1284/fix-language-tools-for-multi-schema-ga

feat(multi schema): updates to GA multi schema

---

.eslintignore
.prettierignore
packages/vscode/package.json
packages/vscode/src/plugins/prisma-postgres-manager/PrismaPostgresRepository.ts
packages/vscode/src/plugins/prisma-postgres-manager/management-api/api.d.ts

refactor: use mgmt-api v1.
