- src/format.ts
- src/lint.ts
The changes done in https://github.com/prisma/prisma-engines/pull/549 requires us to release a new version of the vscode plugin.
> Changing how prisma-fmt takes parameters

- scripts/check-update.sh
`vsce publish` does not like uncommitted files in a git repo. Since we use the file `prisma_version` to track if we need to publish, this failed https://github.com/prisma/vscode/pull/58's first flight: https://github.com/prisma/vscode/runs/503208075
To get around this, we need to commit the file before running `vsce publish`. 
The consequence would be that we get 2 commits for each release. We can squash them into a single commit in a future PR but test the functionality of automated release itself as is for now.
> feat(automate-release): commit the prisma_version

- client/package.json
- server/package.json
- server/src/server.ts
- server/src/util.ts
> Output version of prisma-fmt that is being executed

- .gitattributes
closes #146 
To avoid problems in your diffs and in our scripts, we a .gitattributes file configures Git to properly handle line endings.
Shell scripts need to keep LF (even on Windows systems).
> infra(gitattributes_file_handling_line_endings) 

- .vscode/launch.json
Adds parameter on all debug launch configurations disabling all other extensions during testing locally.
> disable all other extensions while testing out the local extension

- scripts/bump.sh
Using `..` in the description in package.json is not supported.
> fix(CI): use $(..) instead of `..` in script file

- scripts/bump.sh
This was causing the e2e tests to fail becuase the Prisma version in package.json was not set.
> fix(CI): remove undefined parameter in update script

- .github/workflows/publish.yml
- scripts/bump.sh
> improvement(CI): add version to slack notification

- scripts/extension-version.test.js
closes #247 
Removes test cases pointing to four digit versioning scheme and pre GA test cases for extension version as they are no longer needed.
> refactor(test): remove test cases pointing to four digit versioning scheme

- packages/vscode/README.md
- scripts/README_STABLE_BUILD.md
> docs: add quick-fix gif to README

- packages/language-server/.gitignore
- packages/language-server/package.json
- packages/language-server/src/format.ts
- packages/language-server/src/server.ts
- packages/language-server/tsconfig.json
closes #297 
Renames links to old `vscode` to the new `language-tools` repo.
Removes any editor specific stuff from the lsp.
> docs: remove vscode specific text/links from lsp

- .github/workflows/continuous-integration.yml
- .github/workflows/patch-CLI.yml
- .github/workflows/publish-insider-check-CLI.yml
- .github/workflows/publish-insider-push-master.yml
- .github/workflows/publish-stable.yml
When multiple workflows for publishing the Insider extension are running at the same time, one will fail. This PR uses https://github.com/marketplace/actions/action-turnstyle for two scripts to avoid that, by waiting for all other workflows to be finished before starting.
This also triggers CI tests only on pull_requests, since it is redundant otherwise.
> build: serialize workflow runs for insider

- .github/workflows/publish-insider-check-CLI.yml
- .github/workflows/publish-insider-push-master.yml
If the `GITHUB_TOKEN` is at the workflow level, the GH action turnstyle does not get executed correctly.
> chore: add required GITHUB_TOKEN to step.env level

- packages/language-server/src/completion/completionUtil.ts
- packages/language-server/src/completion/completions.json
- packages/language-server/src/completion/completions.ts
- packages/language-server/src/test/completion.test.ts
- packages/vscode/src/test/completion.test.ts
- fixes native types preview features to be shown for datasource block, not for generator block
- adds atomicNumberOperations feature flag to generator block
> chore: atomicNumberOperations and fix datasource previewFeatures flag

- packages/language-server/src/codeActionProvider.ts
closes #472 
Quick-fix adding `previewFeatures = ["nativeTypes"]` to the datasource block if using native Types in the schema but missing this field.
> feat: quick fix for native types error message

- packages/language-server/src/codeActionProvider.ts
The quick-fix that mentions to add `previewFeatures = ["nativeTypes"]` actually inserts `previewFeatures = ["previewFeatures"]`
> fix: quick-fix insert text for native types preview feature

- .eslintrc.js
With the new version of `eslint`, it tries to find a `.tsconfig` in `node_modules`.  Specifying the exact path to the wanted `tsconfig.json` resolves that problem.
> fix: path to project in eslint config since new version

- packages/vscode/package-lock.json
- packages/vscode/src/extension.ts
- packages/vscode/src/telemetryReporter.ts
- scripts/README_INSIDER_BUILD.md
- scripts/README_STABLE_BUILD.md
related to https://github.com/prisma/language-tools/pull/524
Respects the user's decision whether or not to send telemetry events via the `telemetry.enableTelemetry` setting.
> feat: support standard behaviour of opting out of telemetry in VSCode

- packages/vscode/package-lock.json
- packages/vscode/package.json
- renovate.json
regression of `vsce` from version `1.81.0`, therefore pinning version `1.80.0`.
This led to the `node_modules` folder not being included on `vsce package`
> fix: regression of vsce

- packages/language-server/package-lock.json
- packages/vscode/src/extension.ts
- packages/vscode/src/plugins/index.ts
- packages/vscode/src/plugins/prisma-language-server/index.ts
- packages/vscode/src/plugins/types.ts
This is the first of 3 children spawned out of https://github.com/prisma/language-tools/pull/530
It makes managing and extending the functionality of the extension much easier and more manageable.
It is just a wrapper around the VSCode extension API which makes extending and maintaining our VSCode plugin much easier. This is the current API
```typescript
import { ExtensionContext } from 'vscode'
type PluginCommand = {
id: string
action: () => Promise<void> | void
}
export interface PrismaVSCodePlugin {
name: string
commands?: PluginCommand[]
enabled: (context: ExtensionContext) => Promise<boolean> | boolean
activate?: (context: ExtensionContext) => Promise<void> | void
deactivate?: () => Promise<void> | void
}
```
> feat(vscode): pluginify services

- packages/vscode/package-lock.json
- packages/vscode/package.json
- renovate.json
- downgrades `@types/vscode` from `1.50.0` to `1.49.0`
- excludes `vscode` and `@types/vscode` from renovate bot config
Why:
- `@types/vscode` must not have a higher version than the engine `vscode`
> build: remove types/vscode dep from renovate

- packages/language-server/src/completion/completions.ts
- packages/language-server/src/test/completion.test.ts
- packages/language-server/test/fixtures/completions/enumWithComments.prisma
- packages/vscode/src/test/completion.test.ts
- packages/vscode/testFixture/completions/enumWithComments.prisma
> fix: exclude comments from default suggestions

- packages/language-server/src/MessageHandler.ts
Problem: With lsp clients that does'nt support context, nothing is completed at all.
This fix ships completion with `vim-lsp`!
closes https://github.com/prisma/language-tools/issues/578
> fix: not to early return

- packages/language-server/src/rename/renameUtil.ts
- packages/language-server/src/test/rename.test.ts
closes https://github.com/prisma/language-tools/issues/576
> fix: rename with cursor on first/middle position of the word

- packages/language-server/src/prisma-fmt/install.ts
- packages/language-server/src/server.ts
- packages/language-server/src/test/completion.test.ts
- packages/language-server/src/test/format.test.ts
- packages/language-server/src/test/linting.test.ts
At this time, a failed downloading of `prisma-fmt` will result in language server closing with no output, which is difficult to look into.
> feat: optimize for downloading failure

- packages/language-server/src/codeActionProvider.ts
- packages/language-server/src/completion/completions.json
- packages/language-server/src/completion/completions.ts
- removes preview features from datasource block
- adjusts quick fix for adding native types flag to generator block
> chore(native-types): move native types to generator block

- packages/language-server/src/completion/completions.json
- packages/language-server/src/test/completion.test.ts
- packages/vscode/src/test/completion.test.ts
adds `Bytes` and `Decimal` Prisma types
> feat(types): add new scalar types to auto-completion

- packages/language-server/src/server.ts
- packages/vscode/CONTRIBUTING.md
- packages/vscode/package.json
With the setting `prisma.trace.server` the communication between VSCode and the language server can get traced. The default setting is `off`. Options are `messages` and `verbose`. When heading to `Prisma Language Server` output, the logs will be available if turned on.
As Language Servers can be chatty (5 seconds of real-world usage can produce 5000 lines of log), there is a tool to visualize and filter the communication between Language Client / Server. All logs from the channel can be saved into a file, and loaded with the Language Server Protocol Inspector at https://microsoft.github.io/language-server-protocol/inspector
closes #627
> chore(logging): add logging option to VSCode settings

- packages/vscode/syntaxes/prisma.tmLanguage.json
closes https://github.com/prisma/language-tools/issues/638
> fix: missing scalar types in syntax highlighting

- packages/vscode/src/plugins/prisma-language-server/index.ts
fixes #604 
In yarn workspaces packages are symlinked, so chokidar ends up watching all file changes. Setting `followSymlinks: false`, only the symlinks themselves will be watched for changes instead of following the link references and bubbling events through the link's path.
> fix: do not followSymlinks when watching for file changes

- packages/language-server/src/completion/completions.json
- packages/language-server/src/test/completion.test.ts
- packages/vscode/src/test/completion.test.ts
Noticed that `Bytes` and `Decimal` were recognized as Prisma types, but not BigInt. Although these 3 are only really valid with `nativeTypes`, this should be okay since native types are going to be GA soon.
> feat(lang-server): Recognize BigInt as a Prisma type

- packages/language-server/src/server.ts
This was crashing the neovim extension. The binary path we receive from setting can be null if that doesn't exists. This PR introduces a null check for that. 
Thanks!
> fix: check for binary setting existence 

- packages/vscode/package.json
- packages/vscode/src/binaryValidator.ts
- packages/vscode/src/plugins/prisma-language-server/index.ts
- packages/vscode/src/test/binaryValidator.test.ts
- packages/vscode/src/util.ts
> feat: introduce explicit allow prompts for custom binaries

- packages/language-server/src/MessageHandler.ts
- packages/language-server/src/completion/completions.json
- packages/language-server/src/completion/completions.ts
- packages/language-server/src/prisma-fmt/referentialActions.ts
- packages/language-server/src/test/completion.test.ts
- packages/vscode/src/test/completion.test.ts
This gives support for autocompletion of referential actions after points of `onDelete:` or `onUpdate:` in relations. Needs this branch to get merged first: https://github.com/prisma/prisma-engines/pull/1947
Closes: https://github.com/prisma/language-tools/issues/799
> feat: referential action completions

- .github/workflows/4_bump_LSP_in_extension.yml
- packages/language-server/package.json
- packages/language-server/src/prisma-fmt/util.ts
- packages/language-server/src/server.ts
- packages/vscode/release-workflow.md
- scripts/update_package_json_files.js
This makes it possible to log the CLI version again, by writing it to the package.json file the same as the enginesVersion.
Not sure if I got all usages of the `version` (which is now called `enginesVersion`).
> feat: Store and output CLI version again

- packages/language-server/src/completion/completionUtil.ts
- packages/language-server/src/completion/completions.ts
- packages/language-server/src/test/completion.test.ts
- packages/language-server/src/test/prisma-fmt-referentialActions.test.ts
- packages/language-server/test/fixtures/completions/relationDirective.prisma
- packages/vscode/src/test/completion.test.ts
- packages/vscode/testFixture/completions/relationDirective.prisma
Closes https://github.com/prisma/language-tools/issues/818
Adds reliable hardcoded auto-completion + tests for referential actions Cascade, Restrict, NoAction, SetNull, SetDefault
Issue: Restrict will be suggested for SQL server since it's hardcoded.
Hardcoding was the only option right now because prisma-format referential-actions subcommand returns an empty array [] most of the time (probably because it considers the schema invalid)
> fix: completion for referentialActions (Cascade,...)

- scripts/__tests__/extension-version.test.js
Overlap happened with Prisma latest 3.0.1 & 3.1.1
Because npm version is published for `@prisma/language-server` package see:
https://www.npmjs.com/package/@prisma/language-server?activeTab=versions
Tests here show it will be the last overlap happening for 3.x
This will repeat with 4.0 and 4.1, 5.0 and 5.1 until version 31 if nothing is done about it.
https://github.com/prisma/language-tools/issues/868
> test: add tests for minor version bump

- packages/language-server/src/completion/completions.ts
- packages/language-server/src/prisma-fmt/lint.ts
- packages/language-server/src/prisma-fmt/previewFeatures.ts
- The `--no-env-error` flag on `lint` hasn't had effects in a long time.
- The `--datasource-only` flag is never used. There haven't been
datasource preview features in a very long time.
Both these flags are removed from prisma-fmt by https://github.com/prisma/prisma-engines/pull/2222/files
> fix(ls): Remove use of obsolete prisma-fmt flags

- packages/vscode/src/plugins/prisma-language-server/index.ts
When using 
```
const watchedPaths = watcher.getWatched();
console.log(watchedPaths)
```
I could see that the `.bin` folder inside node_modules was being watched unnecessarily.
ignore parameter filters dot folders except `.prisma` meaning the watcher should now watch less folders/files
Related https://github.com/prisma/language-tools/issues/786
> fix(vscode): watcher ignore dotfiles except .prisma

- packages/vscode/src/plugins/prisma-language-server/index.ts
Because:
and
```
/**
* List of workspace folders or `undefined` when no folder is open.
* *Note* that the first entry corresponds to the value of `rootPath`.
*/
export const workspaceFolders: ReadonlyArray<WorkspaceFolder> | undefined;
```
> chore: replace deprecated rootPath

- packages/language-server/src/completion/completions.json
- packages/language-server/src/test/completion.test.ts
- packages/vscode/src/test/completion.test.ts
adds auto completion for `dataproxy`
```
generator myGenerator {
engineType = // "library" or "binary" or "dataproxy"
}
```
closes https://github.com/prisma/language-tools/issues/886
> feat: add dataproxy completion

- packages/language-server/src/prisma-fmt/format.ts
- packages/language-server/src/prisma-fmt/lint.ts
- packages/language-server/src/prisma-fmt/nativeTypes.ts
- packages/language-server/src/prisma-fmt/previewFeatures.ts
- packages/language-server/src/prisma-fmt/referentialActions.ts
The logs will appear in the `Output` tab at the bottom of the UI. On the
dropdown on the right, select `Prisma Language Server`.
> feat: Log when one of the functions exported from prisma-fmt-wasm is called

- packages/language-server/src/server.ts
Unless there is a good reason to mix this into each other, I think this should be cleaner this way.
> chore(language-server): Log first in onInitialize, then handle capabilities

- packages/language-server/src/completion/completions.json
Closes https://github.com/prisma/language-tools/issues/942
> fix(autocompletion): filter out Restrict for sqlserver

- packages/language-server/src/server.ts
- packages/vscode/package.json
- packages/vscode/src/plugins/prisma-language-server/index.ts
Closes https://github.com/prisma/language-tools/issues/944
Implemented as a boolean
Shows in the UI like
With commands to set it on/off easily
> feat: enable/disable File Watcher setting + commands

- packages/language-server/src/MessageHandler.ts
- packages/language-server/src/prisma-fmt/format.ts
tabSize is now taken into account again. I confirmed this through manual
testing.
closes https://github.com/prisma/language-tools/issues/993
> fix: Use the new prisma-fmt format param

- packages/vscode/package.json
- packages/vscode/syntaxes/prisma.markdown.json
This PR proposes to add a `prisma.markdown.json` file that adds fenced code block highlighting for Prisma schema syntax in markdown fenced code blocks.
References: https://github.com/microsoft/vscode/blob/main/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json
> feat(syntax): add markdown fenced code block highlighting

- .github/workflows/6_build.yml
- .github/workflows/PR_build_extension.yml
- packages/vscode/package.json
Related https://github.com/prisma/language-tools/issues/1005
> ci: build extension for each PR

- scripts/e2eTestsOnVsix/install_extension.js
Broken since update dependency @vscode/test-electron to v2
https://github.com/prisma/language-tools/pull/1101
See https://github.com/microsoft/vscode-test
> ci: fix e2e tests

- scripts/e2eTestsOnVsix/extension_version.sh
Example: https://github.com/prisma/language-tools/runs/6075506873?check_suite_focus=true#step:6:4
See https://prisma-company.slack.com/archives/C02L83FKUTS/p1650362173763509
> ci: extension_version, fail if vsce cmd returns empty version

- packages/language-server/src/__test__/completion.test.ts
- packages/language-server/src/__test__/jumpToDefinition.test.ts
- packages/language-server/src/completion/completionUtils.ts
- packages/language-server/src/completion/completions.ts
- packages/language-server/src/previewFeatures.ts
- packages/language-server/test/fixtures/correct_mongodb.prisma
extendedIndexes will be GA in next release
dataProxy is already GA
Why? Because after a feature goes GA we cannot scope the completion to the `previewFeatures` flag anymore.
> fix(language-server): update previewFeatures that are or will be GA

- packages/language-server/src/__test__/completion.test.ts
- packages/language-server/src/completion/completions.ts
Closes https://github.com/prisma/language-tools/issues/1139
schema for manual testing
```prisma
datasource db {
provider = "postgresql"
url      = env("DATABASE_URL")
}
model ops {
id    Int @id
title   String
content String
@@index([title( )], type: Gist)
//                 ^ sort, ops
}
model type {
id    Int @id
title   String
content String
@@index([title], )
//                  ^ fields, map, type
}
model A {
id  Int    @id
title String @db.Inet
@@index([title(ops: )], type: Gist)
//                   ^ See the native type of `title` is `Inet` and
//                     the index type is GiST
//                     it suggests `InetOps` & `raw`.
}
model B {
id  Int    @id
title String @db.Inet
@@index([title], type: )
//                       ^ Gist, Gin, SpGist, Brin, Hash or BTree …
```
> feat(ls): completions for PostgreSQL index types

- packages/language-server/src/__test__/completion.test.ts
- packages/language-server/src/completion/completionUtils.ts
- packages/language-server/src/completion/completions.ts
closes https://github.com/prisma/language-tools/issues/1084
Added `@id` suggestion after an enum
> fix(completion): suggest @id for enum and ignore comments

- packages/language-server/package-lock.json
- packages/language-server/package.json
- packages/vscode/package-lock.json
- packages/vscode/package.json
https://code.visualstudio.com/updates/v1_56
This is a major Electron release and comes with Chromium 89.0.4389.114 and Node.js 14.16.0.
Also, for language-server: change `engines` for Node.js version from 10 to 14
Related https://github.com/prisma/language-tools/issues/1207
> chore: change min VS Code from 1.52.0 to 1.56.0

- packages/language-server/src/MessageHandler.ts
- packages/language-server/src/__test__/documentSymbol.test.ts
- packages/language-server/src/__test__/jumpToDefinition.test.ts
- packages/language-server/src/completion/completionUtils.ts
- packages/language-server/src/rename/renameUtil.ts
- packages/language-server/src/server.ts
- packages/language-server/src/util.ts
Partially resolves #751, resolves #1031
It only provides top-level symbols (`datasource`, `generator`, `model`, `enum` and `type`), the main usage is to get sticky scroll working:
All supported symbols and their corresponding icons in Outline view:
This PR also changes "Go To Definition" to highlight only the type name, like what TypeScript language server does.
A simple test was added againest the existing `hover.prisma` fixture file.
Providing fields requires much more time to do refactoring, which I don't have now.
> feat: Support providing top-level elements as symbols

- packages/language-server/src/__test__/completion.test.ts
- packages/language-server/src/__test__/quickFix.test.ts
- packages/language-server/src/completion/completionUtils.ts
- packages/language-server/src/completion/completions.ts
> fix(autocomplete): @datasourcename

- packages/language-server/src/MessageHandler.ts
- packages/language-server/src/__test__/linting.test.ts
- packages/language-server/src/diagnosticsHandler.ts
- packages/language-server/test/fixtures/linting/@@ignore.prisma
- packages/language-server/test/fixtures/linting/@ignore.prisma
> feat: dim @ignore fields and @@ignore models

- packages/language-server/src/__test__/completion.test.ts
- packages/language-server/src/completion/completions.json
- packages/language-server/src/completion/completions.ts
- packages/language-server/src/previewFeatures.ts
WHEN
```prisma
generator client {
previewFeatures = ["postgresqlExtensions"]
}
datasource db {
provider = "postgres(ql)"
| << "extensions = []"
}
```
closes #1265
> feat(ls): Autocomplete datasource field "extensions"

- flake.lock
- flake.nix
- nix/delete-node-modules.nix
- nix/format-project.nix
- nix/shell.nix
- nix/vscode.nix
https://github.com/hercules-ci/flake-parts/
- The library is small, and the main value proposition is the modules system, that many/most nix users are already very familiar with from home-manager/nixos configuration.
- Gluing different projects in a repo together becomes standardized, and not manual like what I had implemented for prisma-fmt-wasm.
- The modules are more composable and easier to isolate in smaller files. We can add more options to the modules if we want.
- The config options are typed and validated.
> nix: use flake-parts

- nix/prisma-language-server.nix
At first we hardcoded the --stdio argument, then I decided to not do that anymore, and forgot to manually test this. The result is that we can't pass arguments to the language server (mostly --stdio).
This commit fixes that (I tried it, this time).
> nix: accept arguments in language server wrapper

- packages/language-server/src/__test__/completion.test.ts
- packages/language-server/src/completion/completionUtils.ts
- packages/language-server/src/completion/completions.ts
- Added test to ensure that `@map` is not suggested when already present in line 
- Updated another test to ensure that it does still show when already present on another line
- Minor refactoring
closes #1079
> Suggest @map when not already present in line

- packages/vscode/src/util.ts
> Updated wording for Stable & Insiders detection

- packages/language-server/src/__test__/completion.test.ts
- packages/language-server/src/completion/completions.json
- packages/language-server/src/completion/completions.ts
- packages/language-server/src/previewFeatures.ts
closes https://github.com/prisma/prisma/issues/16920
Workaround until we get we can manage to get these in engines
> feat: `schemas` completion within datasource

- packages/language-server/src/MessageHandler.ts
- packages/language-server/src/__test__/documentSymbol.test.ts
- packages/language-server/src/__test__/format.test.ts
- packages/language-server/src/__test__/hover.test.ts
- packages/language-server/src/__test__/jumpToDefinition.test.ts
- packages/language-server/src/__test__/linting.test.ts
- packages/language-server/src/__test__/quickFix.test.ts
- packages/language-server/src/__test__/rename.test.ts
- packages/language-server/src/codeActionProvider.ts
- packages/language-server/src/completion/completions.ts
- packages/language-server/src/rename/renameUtil.ts
`TextDocument` in `vscode-languageserver` was marked as deprecated
-> use `vscode-languageserver-textdocument`
-> clean up `TextDocument` imports
closes #1421
> clean(ls): clean up TextDocument usage

- packages/vscode/package-lock.json
- packages/vscode/package.json
- packages/vscode/src/plugins/prisma-language-server/index.ts
This PR works with https://github.com/prisma/prisma/pull/19457, we now send a simpler signal for when we need to reload types via our extension, instead of watching many possible paths.
closes https://github.com/prisma/prisma/issues/13946
> fix(vscode): ts server restart on file change

- packages/language-server/src/MessageHandler.ts
Based on @Druue  's [comment](https://github.com/prisma/language-tools/issues/1247#issuecomment-1344111645), I have identified the bug.
The issue lies in the implementation of `handleDefinitionRequest` within `MessageHandler.ts`. It currently employs a workaround to determine the starting position of all potential blocks. However, the criterion used does not correctly identify lines that are actually fields within a block. To address this, I propose a simple fix: filtering out any matches that is not found by the start line of a block.
I have tested this fix and it works perfectly for the following cases:
1. Original case from #1247
```
enum PostType {
A
B
}
model Post {
id   String   @id
type PostType
userId String
user   User   @relation(fields: [userId], references: [id])
}
model User …
```
> fix(ls): `handleDefinitionRequest` fails to locate the correct block when multiple names are present within the same block (issue #1247)

- packages/language-server/src/__test__/completion.test.ts
- packages/language-server/src/completion/completions.json
Not used anymore since https://github.com/prisma/prisma/releases/tag/5.2.0 
See https://github.com/prisma/prisma/pull/20692
> fix(completion): remove engineType=dataproxy

- packages/vscode/syntaxes/prisma.tmLanguage.json
> fix(vc): bigint to be recognised as a scalar field and use that colour

- packages/language-server/src/__test__/completion.test.ts
- packages/language-server/src/codeActionProvider.ts
- packages/language-server/src/completion/completions.ts
- packages/language-server/src/rename/renameUtil.ts
- packages/language-server/src/util.ts
- Updated getAllRelationNames to be able to take different regex filters.
- Updated completions to offer composite types as field type completions.
fixes #1495
> fix(LS): offer composite types as field type completions

- packages/language-server/src/MessageHandler.ts
- packages/language-server/src/__test__/documentSymbol.test.ts
- packages/language-server/src/__test__/hover.test.ts
- packages/language-server/src/util.ts
- packages/language-server/test/fixtures/hover_postgresql.prisma
> fix(ls): support multiline comments in hover

- packages/language-server/src/__test__/completion.test.ts
- packages/language-server/src/completion/completionUtils.ts
> fix(ls): no more completions for attributes that are already present

- .github/workflows/1_2_b_bump_extension_only.yml
- .github/workflows/1_2_c_promote_patch_to_stable.yml
- .github/workflows/1_check_for_updates.yml
- .github/workflows/2_bump_versions.yml
- .github/workflows/3_LS_tests_publish.yml
- .github/workflows/4_bump_LS_in_extension.yml
- .github/workflows/5_e2e_tests.yml
- .github/workflows/6_build.yml
- .github/workflows/7_publish.yml
- .github/workflows/PR_build_extension.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/e2e_check_for_new_published_vsix.yml
- .github/workflows/e2e_published_vsix.yml
Since Node.js 16 is EOL for a while already, tooling does not support it anymore.
Example: ovsx failed to publish 5.12.0 yesterday -> https://github.com/prisma/language-tools/actions/runs/8523249444/job/23345119163#step:8:12
```
ovsx requires at least NodeJS version 18. Check your installed version with `node --version`.
```
Renovate PR for the update:
https://github.com/prisma/language-tools/pull/1692
This will not change our confidence regarding supporting old versions of VS Code since we test the oldest one we support in https://github.com/prisma/language-tools/blob/0528403aafa98820d003e194d94d69d1f4a133b4/packages/vscode/src/__test__/runTest.ts#L43-L46
> ci: switch from Node.js 16 to 18

- packages/vscode/package.json
- packages/vscode/src/CodeLensProvider.ts
- packages/vscode/src/plugins/prisma-language-server/index.ts
Added a codelens provider to our vscode extension with one codelens command to generate your Prisma client
This uses new config to define which script runner to use and whether you want the codelens active or not
```
prisma.enableCodeLens: [true, false] // default: true
prisma.scriptRunner: ["npx", "pnpm", "yarn"] // default: npx
```
This shows the following clickable text above the generator block
Which opens up a new output window wherein we run `prisma generate` using the defined script runner
https://github.com/prisma/language-tools/assets/29753584/118f61dc-dc09-4fe8-b1ec-0ff610efe6e4
closes https://github.com/prisma/language-tools/issues/1651
> feat(vscode): Add codelens provider w/ generate client command

- packages/language-server/src/lib/MessageHandler.ts
- packages/language-server/src/lib/Schema.ts
- packages/language-server/src/lib/ast/block.ts
- packages/language-server/src/lib/ast/configBlock.ts
- packages/language-server/src/lib/ast/findAtPosition.ts
- packages/language-server/src/lib/ast/relations.ts
- packages/language-server/src/lib/code-actions/index.ts
- packages/language-server/src/lib/code-actions/rename.ts
- packages/language-server/src/lib/completions/attributes.ts
- packages/language-server/src/lib/completions/blocks.ts
- packages/language-server/src/lib/completions/generator.ts
- packages/language-server/src/lib/completions/index.ts
- packages/language-server/src/lib/completions/types.ts
- packages/language-server/src/lib/validations.ts
Introduces abstractions over schema files that in future would allow us to support multiple schemas files.
At the moment, this does not yet means Language tools support split schema - we are still working with a single files in there. 
Abstractions I am talking about:
- `SchemaDocument` - single `.prisma` document, part of the schema. Can be created either from `TextDocument` supplied by language tools or file read from the disk.
- `Line` - slightly nicer abstraction over single line of text, main point of it's existence - pointer back to `SchemaDocument` that contains it.
- `PrismaSchema` - collection of schema documents comprising a single DB schema. Allows to iterate over lines of all of the contained files. For the most parts, this replaces `lines: string[]` array as an input of …
> Preparatory refactor for split schema support

- packages/vscode/package.json
- packages/vscode/src/extension.ts
- packages/vscode/src/notifications.ts
- packages/vscode/src/plugins/prisma-language-server/index.ts
closes https://github.com/prisma/team-orm/issues/1132
> feat(vsc): Add PDP notification

- packages/language-server/package-lock.json
- packages/language-server/package.json
- packages/language-server/src/__test__/artificial-panic.test.ts
- packages/language-server/src/__test__/completion.test.ts
- packages/language-server/src/__test__/format.test.ts
- packages/language-server/src/__test__/helper.ts
- packages/language-server/src/__test__/hover.test.ts
- packages/language-server/src/__test__/jumpToDefinition.test.ts
- packages/language-server/src/__test__/linting.test.ts
- packages/language-server/src/__test__/quickFix.test.ts
- packages/language-server/src/__test__/rename.test.ts
- packages/language-server/src/lib/DiagnosticMap.ts
- packages/language-server/src/lib/MessageHandler.ts
- packages/language-server/src/lib/Schema.ts
- packages/language-server/src/lib/ast/block.ts
- packages/language-server/src/lib/ast/configBlock.ts
- packages/language-server/src/lib/code-actions/index.ts
- packages/language-server/src/lib/completions/index.ts
- packages/language-server/src/lib/prisma-schema-wasm/format.ts
- packages/language-server/src/lib/prisma-schema-wasm/lint.ts
- packages/language-server/src/lib/prisma-schema-wasm/textDocumentCompletion.ts
- packages/language-server/src/lib/validations.ts
- packages/language-server/src/server.ts
- scripts/update_package_json_files.js
Use `@prisma/schema-files-loader` to resolve schema files from
memory or disk.
See also https://github.com/prisma/prisma/pull/24085
Message handler's methods now accept `PrismaSchema` instance from
outside, rather than creating it from a single document. Singatures of
the methods are also adjusted to consistently be in `(schema,
intitianigDocument, params)` form.
As per our Slack discussion, tests are split into it's own task: prisma/team-orm#1140
Contribute to https://github.com/prisma/team-orm/issues/1042
> Split schema support

- packages/vscode/src/CodeLensProvider.ts
pass cwd directly to exec instead of cd
fixes #1738
> fix(vsc): generate codelens on windows

- packages/language-server/src/__test__/linting/single-file.test.ts
- packages/language-server/src/lib/MessageHandler.ts
amend wording to be inclusive of non-vscode usage
[internal slack thread](https://prisma-company.slack.com/archives/C076D0YJQQN/p1718635735239969)
> chore(ls): preview features error message wording

- packages/language-server/src/__test__/rename/multi-file.test.ts
- packages/language-server/src/__test__/rename/single-file.test.ts
- packages/language-server/src/lib/code-actions/rename.ts
fixes https://github.com/prisma/language-tools/issues/1771
> fix(LS): rename where map doesn't exist

- packages/vscode/src/__test__/runTest.ts
We're seeing errors in our vs code e2e test suites but we're not capturing the error message so we don't see _why_ it's erroring
https://github.com/prisma/language-tools/actions/runs/10073180669/job/27846678324
> chore(vscode): capture error message if electron test suite fails

- packages/vscode/src/__test__/runTest.ts
Adds some args that hopefully give us more info as to what's going on 🤞
> chore(vscode): increase logging scope of vscode test suite

- packages/vscode/package-lock.json
- packages/vscode/package.json
Bump the minimal supported VSCode version from 1.56 (April 2021) to 1.85
(November 2023). This fixes the e2e tests.
> chore: bump minimal supported VSCode version from 1.56 to 1.85

- packages/vscode/src/util.ts
there is a minor repetition error in the sentence. The word “both” is repeated twice.
> chore: fix typo in vscode/src/util.ts

- packages/vscode/syntaxes/prisma.tmLanguage.json
This PR follows up https://github.com/prisma/language-tools/pull/1806 ([see Slack](https://prisma-company.slack.com/archives/C058VM009HT/p1734381823284309)).
> fix(vscode): fix syntax highlightning

- .github/workflows/2_bump_versions.yml
A double version bump can currently occur when the prisma CLI update check succeeds twice for the same version and spawns two bump version jobs. It can happen because the job runs on a 5 minute cron (and the cron is not reliable, it run twice within 2 minutes yesterday).
Normally git would prevent one from the bump commits from being pushed, but if the two bump jobs end up checking out and pushing one after another they maintain linear history and successfully push two version bumps. This is easy to prevent though - we can check if the version we intend to bump to is already in the file. If it is, then some job has bumped it before us and if it hasn't happened yet the two jobs will race and only one will successfully `git push`.
> fix: prevent double version bumps

- packages/language-server/src/lib/Schema.ts
`config.schema` is now `string | undefined` and not a union type.
> fix(language-server): adapter for prisma config changes

- packages/language-server/src/__test__/completions/single-file.test.ts
- packages/language-server/src/lib/completions/completions.json
Adding syntax support for the new engine type `client`. See https://github.com/prisma/prisma/pull/26092
> [!WARNING]
> Should only be merged once we actually merge and ship the query compiler. ;)
> feat(query compiler): add client engine type to completions

- packages/vscode/fixtures/format/expected.prisma
Reverts the assertion change because it seems to be a legitimate bug
> chore: revert "fix: update expected format (#1830)"

- packages/language-server/src/__test__/completions/single-file.test.ts
- packages/language-server/src/lib/completions/functions.ts
- packages/language-server/src/lib/completions/index.ts
I noticed they where missing in the vscode extension.
> feat: add ULID and NanoID completions to language server

- packages/vscode/package.json
Currently the extension is activated every time that a javascript or typescript file is opened, even if no related prisms file is present in the workspace...
With this PR, the extension is activated when a  file with `prisma` extension is opened or exists in the workspace
Fix https://github.com/prisma/language-tools/issues/1815
> fix(vscode): fix activation events

- .github/workflows/PR_build_extension.yml
This step is consistently failing on CI and the [github action it uses](https://github.com/gavv/pull-request-artifacts) is not supported anymore and was archived by the maintainer.
=> Let's drop this and live with only the default github actions artifact storage.
> chore: remove artifact uploading to custom branch

- .github/workflows/1_2_b_bump_extension_only.yml
- .github/workflows/1_2_c_promote_patch_to_stable.yml
- packages/vscode/CONTRIBUTING.md
- scripts/setup_branch.sh
This PR fixes the patch release CI and updates the related documentation to be more clear.
> chore: fix patch release CI

- packages/vscode/package-lock.json
- packages/vscode/package.json
- packages/vscode/src/plugins/prisma-postgres-manager/commands/login.ts
- packages/vscode/src/plugins/prisma-postgres-manager/index.ts
- packages/vscode/src/plugins/prisma-postgres-manager/management-api/auth.ts
This PR just adds the basic OAuth handling. Storing and using the tokens is coming in an upcoming PR that also connects in the API.
Note that refresh token handling is also a pending task and not yet supported by the backend.
Note: Targeting `manage-ppg` branch for now so we can still release ORM hotfixes without reverting work for the manage ppg extension.
> feat: ORM-934 add oauth login

- .github/workflows/update-api-types.yml
Workflow is currently failing due to missing git credentials. This script is already used by the other workflows that bump versions.
Tested workflow run here: https://github.com/prisma/language-tools/actions/runs/15133313479 (force pushed this branch afterwards to revert changes done by the workflow - wanna test this on main then again ;) )
> chore(api-types): add missing git credentials step

- packages/vscode/package-lock.json
- packages/vscode/package.json
zod v3.25.x which includes the new zod v4 stuff seems to be very unstable and breaks our build. They also issues 20 patch releases for 3.25 in the last 48h. As it seems not a safe bet to use this yet. Espeically not in our non-esm project here. Switching back to an older more stable version for now.
> fix: use stable zod version 3.24.3

- packages/vscode/package.json
> [!NOTE]
> There are some issues with zod because of which this build fails. https://github.com/prisma/language-tools/pull/1857 addresses that.
> feat: ORM-995 update copy on auth panel

- packages/vscode/package.json
- packages/vscode/src/plugins/prisma-postgres-manager/PrismaPostgresRepository.ts
- packages/vscode/src/plugins/prisma-postgres-manager/commands/createProjectInclDatabase.ts
- packages/vscode/src/plugins/prisma-postgres-manager/commands/createRemoteDatabase.ts
- packages/vscode/src/plugins/prisma-postgres-manager/commands/deleteProject.ts
- packages/vscode/src/plugins/prisma-postgres-manager/commands/deleteRemoteDatabase.ts
- packages/vscode/src/plugins/prisma-postgres-manager/commands/getRemoteDatabaseConnectionString.ts
- packages/vscode/src/plugins/prisma-postgres-manager/commands/launchStudio.ts
- packages/vscode/src/plugins/prisma-postgres-manager/commands/login.ts
- packages/vscode/src/plugins/prisma-postgres-manager/index.ts
- packages/vscode/src/plugins/prisma-postgres-manager/shared-ui/handleCommandError.ts
This PR streamlines various messages and fixes issues with getting the correct error message out of API errors.
Principles I tried to follow:
- Use short messages and names (e.g. `Delete Project` instead of `Delete Prisma Postgres Project`)
- Command failures name the command that failed. (e.g. `Delete Remote Database failed: You are not allowed to delete the default environment.`)
- Do not include additional names, regions etc info in success messages to keep them short and simple
> feat: ORM-992 streamline copy and error messages

- packages/vscode/package-lock.json
- packages/vscode/package.json
- packages/vscode/src/getPackageJSON.ts
- packages/vscode/src/plugins/prisma-postgres-manager/commands/deployLocalDatabase.ts
- packages/vscode/src/plugins/prisma-studio/commands/launch/openNewStudioTab.ts
- packages/vscode/src/plugins/prisma-studio/commands/launch/startStudioServer.ts
Hey 👋 
closes EXP-1687
closes EXP-1456
`product` names were off in telemetry events for `dev` and `studio`.
> fix: telemetry product names.
